### ISSUE TITLE
Add notebook prop to services -- [SA/CSI]

### ISSUE THREAD

**Issue by Fiskey111** [Fiskey111/L.S.Noire#19]
Utilize the following code to add a notebook to the paramedics/coroner to increase realism.

`            _notepad = new Rage.Object("prop_notepad_01", _doc.Position);
            int boneId = _doc.GetBoneIndex(PedBoneId.LeftPhHand);
            NativeFunction.CallByName<uint>("ATTACH_ENTITY_TO_ENTITY", _notepad, _doc, boneId, 0f, 0f, 0f, 0f, 0f, 0f, true, false, false, false, 2, 1);`

**Comment by LtFlash** [comment]
Added.
