### ISSUE TITLE
Unable to add new Scripts to Queue Dynamically -- [SA/ALL]

### ISSUE THREAD

**Issue by Fiskey111** [Fiskey111/L.S.Noire#23]
Produces error found here: [http://pastebin.com/nqjVuTPT](url)

Utilized in SA_1_CSI

**Comment by LtFlash** [comment]
Discussed in Discord
`Exception message: GetScriptById: Script with id [SA_2b_MedicalExaminer] does not exist.`
All scripts have to be registered to a script manager before trying to start them.
